version: '3.4'
services:
  restApplication:
    image: antoniowillianjr/spring_boot_app_image
    restart: always
    build: 
      context: .
      dockerfile: ./dockerBuild/Dockerfile
    working_dir: /dockerBuild
    environment:
      TZ: America/Sao_Paulo
      SPRING-BOOT-ENVIRONMENT: Production
    volumes:
      - ./dockerBuild:/dockerBuild
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    networks:
      - udemy-network
volumes:
    restApplicationVol:
networks:
    udemy-network:
        driver: bridge
